Minor changes to get successfull v++ build with request/response ports
Some can probably be reverted

[XRT] ERROR: Invalid scalar argument size, expected 4 got 8
ERROR: clSetKernelArg() for kernel "krnl", argument index 0.
host.cpp:74 Error calling err = krnl1.setArg(0, buffer_memory), error code is: -51